# Generated by Django 4.2.1 on 2023-05-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('impuesto_inmobiliario', models.FileField(upload_to='impuestos/')),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
