# Generated by Django 4.2.1 on 2023-05-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler'), ('Alquiler Temporario', 'Alquiler Temporario'), ('Tasaciones', 'Tasaciones')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='properties/')),
                ('image2', models.ImageField(upload_to='properties/')),
                ('image3', models.ImageField(upload_to='properties/')),
                ('image4', models.ImageField(upload_to='properties/')),
                ('image5', models.ImageField(upload_to='properties/')),
            ],
        ),
    ]
