# Generated by Django 4.2.1 on 2023-05-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image5',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inmobiliaria.property')),
            ],
        ),
    ]
