# Generated by Django 4.2.1 on 2023-05-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_remove_property_image1_remove_property_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Sin ubicación', max_length=255),
        ),
    ]
