# Generated by Django 4.2.1 on 2023-05-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='alquilado',
            field=models.BooleanField(default=False),
        ),
    ]
